---
title: "Crane Wine Cellar"
output: 
  flexdashboard::flex_dashboard:
    css: static/style.css
    vertical_layout: fill

---

<!--html_preserve-->
<style>
@import url('https://fonts.googleapis.com/css?family=Caveat|Source+Sans+Pro&display=swap');
</style>
<!--/html_preserve-->

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(summarytools)
library(httr)
library(DT)
library(colorspace)
library(vapoRwave)
```

```{r data}
# usethis::edit_r_environ()
url_list <- sprintf("https://www.cellartracker.com/xlquery.asp?User=%s&Password=%s&Format=csv&Table=List", 
               Sys.getenv("CELLAR_TRACKER_USER"), 
               Sys.getenv("CELLAR_TRACKER_PASS"))
url_availability <- sprintf("https://www.cellartracker.com/xlquery.asp?User=%s&Password=%s&Format=csv&Table=Availability", 
                    Sys.getenv("CELLAR_TRACKER_USER"), 
                    Sys.getenv("CELLAR_TRACKER_PASS"))

response_list <- httr::GET(url_list)
response_availability <- httr::GET(url_availability)

wine_cellar <- content(response_list, type = "text/csv", encoding = "ISO-8859-1")
availability <- content(response_availability, type = "text/csv", encoding = "ISO-8859-1")

#wine_cellar <- read_csv("My Cellar.csv", na = c("", "NA", 9999), locale = locale(encoding = "ISO-8859-1"))
#view(dfSummary(wine_cellar))

wine_cellar <- 
  wine_cellar %>% 
  unite("RegionCountry", c(Region, Country), sep = ", ")
```

Sidebar {.sidebar}
=======================================================================

<br />

#### What do you want tonight?

These are the data on my personal cellar, as tracker in CellarTracker.com. 


Wines 
=======================================================================

Column {data-width=600}
-----------------------------------------------------------------------

### Consume Range

```{r fig.height=12, fig.width=12}
# Consume Range
wine_cellar %>% 
  mutate(Wine = fct_rev(fct_reorder(Wine, EndConsume))) %>%
  ggplot() +
  geom_segment(aes(x = Wine, xend = Wine, y = BeginConsume, yend=EndConsume), color = "grey") +
  geom_point(aes(x = Wine, y = BeginConsume), color = sequential_hcl(5, "Blues 2")[3], size = 3 ) +
  geom_point(aes(x = Wine, y = EndConsume), color = sequential_hcl(5, "Blues 2")[1], size = 3 ) +
  theme_minimal(base_family = 'Avenir') +
  theme(axis.text.y = element_text(size = 14)) +
  coord_flip() +
  geom_hline(yintercept = 2019) +
  labs(x = "", y = "Consume between")
```

Column {data-width=400}
-----------------------------------------------------------------------
   
### Varietal

```{r}
# Inventory by Varietal
wine_cellar %>% 
  mutate(MasterVarietal = fct_rev(fct_infreq(MasterVarietal))) %>%
  ggplot(aes(x = MasterVarietal)) +
  #geom_bar(fill = sequential_hcl(1, "Blues 2")) +
  geom_bar(fill = vapoRwave:::jazzCup_palette[3]) +
  coord_flip() +
  theme_minimal(base_family = 'Avenir') +
  theme(panel.grid.major.y = element_blank()) +
  scale_y_continuous(expand = c(0, 0), breaks = c(1,5,10,15,20)) +
  labs(x = "", y = "Wines")
```   
    
### Region

```{r}
# Inventory by Region
wine_cellar %>% 
  mutate(RegionCountry = fct_rev(fct_infreq(RegionCountry))) %>%
  ggplot(aes(x = RegionCountry)) +
  #geom_bar(fill = sequential_hcl(1, "Blues 2")) +
  geom_bar(fill = vapoRwave:::jazzCup_palette[3]) +
  coord_flip() +
  theme_minimal(base_family = 'Avenir') +
  theme(panel.grid.major.y = element_blank()) +
  scale_y_continuous(expand = c(0, 0), breaks = c(1,5,10,15,20)) +
  labs(x = "", y = "Wines")
```

Availability {data-orientation=rows}
=======================================================================

Row {data-height=200}
-----------------------------------------------------------------------
   
### Next 5

```{r}
# Next 5
availability %>% 
  arrange(desc(Available)) %>% 
  slice(1:5) %>% 
  select(Available, Wine, Vintage, MasterVarietal, Producer, Country, Region, CScore, ComBegin, ComEnd) %>% 
  mutate(Available = round(Available, digits = 3)) %>% 
  knitr::kable()
```   
    
Row
-----------------------------------------------------------------------

### Unreported Availability

```{r}
# Unreported Availability
availability %>% 
  filter(is.na(Available)) %>% 
  select(Available, Wine, Vintage, MasterVarietal, Producer, Country, Region, CScore) %>% 
  knitr::kable()
```

List {data-orientation=rows}
=======================================================================

Row {data-height=650}
-----------------------------------------------------------------------

### Complete List

```{r}
wine_cellar %>% datatable(class = 'compact row-border nowrap', options = list(pageLength = 20))
```
